# Generated by Django 6.0.6 on 2026-06-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorparameter',
            name='station',
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(default='AWS-UG-001', help_text='Raw station ID string from ESP32 e.g. AWS-UG-001', max_length=50)),
                ('timestamp', models.DateTimeField(help_text='Timestamp from the ESP32 RTC. ESP32 key: Time')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='When this server received the reading')),
                ('pressure', models.FloatField(blank=True, help_text='Air pressure in hPa. ESP32 key: Press', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='Altitude in meters. ESP32 key: Alt', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='Air temperature in Celsius. ESP32 key: Temp', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='Relative humidity in percent. ESP32 key: Hum', null=True)),
                ('light', models.FloatField(blank=True, help_text='Light level in lux. ESP32 key: Light', null=True)),
                ('soil_moisture', models.FloatField(blank=True, help_text='Soil moisture voltage. ESP32 key: SoilM', null=True)),
                ('rain', models.IntegerField(blank=True, help_text='Rain gauge tip count. ESP32 key: Rain', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='Wind speed in km/h. ESP32 key: WSpd', null=True)),
                ('wind_direction', models.IntegerField(blank=True, help_text='Wind direction in degrees. ESP32 key: WDir', null=True)),
                ('volt_3v3', models.FloatField(blank=True, help_text='3.3V rail voltage. ESP32 key: V33', null=True)),
                ('volt_5v', models.FloatField(blank=True, help_text='5V rail voltage. ESP32 key: V5', null=True)),
                ('volt_batt', models.FloatField(blank=True, help_text='Battery voltage. ESP32 key: VBatt', null=True)),
                ('volt_solar', models.FloatField(blank=True, help_text='Solar panel voltage. ESP32 key: VSol', null=True)),
                ('volt_dc', models.FloatField(blank=True, help_text='DC input voltage. ESP32 key: VDC', null=True)),
                ('curr_batt', models.FloatField(blank=True, help_text='Battery current in Amps. ESP32 key: CBatt', null=True)),
                ('curr_solar', models.FloatField(blank=True, help_text='Solar current in Amps. ESP32 key: CSol', null=True)),
                ('station', models.ForeignKey(blank=True, help_text='Link to registered Station.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='stations.station')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.DeleteModel(
            name='SensorParameter',
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['timestamp'], name='idx_timestamp'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['station_code'], name='idx_station_code'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['station_code', 'timestamp'], name='idx_code_time'),
        ),
    ]
