# Generated by Django 5.2.3 on 2026-06-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('expected_interval_minutes', models.IntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='stations.sensorparameter')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='sensorparameter',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='stations.station'),
        ),
        migrations.CreateModel(
            name='StationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('full', 'Perfectly Transmitting'), ('partial', 'Partially Transmitting'), ('down', 'Down')], default='down', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('computed_by', models.CharField(default='rule_based', max_length=50)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='stations.station')),
            ],
        ),
    ]
