# Generated by Django 5.2.3 on 2026-07-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='station',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='station',
            name='sensors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
