# Generated by Django 6.0.6 on 2026-07-04 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_remove_sensorparameter_station_sensorreading_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(default='AWS-UG-001', max_length=50)),
                ('timestamp', models.DateTimeField(help_text='ESP32 key: Time')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('curr_batt', models.FloatField(blank=True, help_text='ESP32 key: CBatt', null=True)),
                ('curr_solar', models.FloatField(blank=True, help_text='ESP32 key: CSol', null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_readings', to='stations.station')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='idx_current_timestamp'), models.Index(fields=['station_code', 'timestamp'], name='idx_current_code_time')],
            },
        ),
        migrations.CreateModel(
            name='VoltageReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(default='AWS-UG-001', max_length=50)),
                ('timestamp', models.DateTimeField(help_text='ESP32 key: Time')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('volt_3v3', models.FloatField(blank=True, help_text='ESP32 key: V33', null=True)),
                ('volt_5v', models.FloatField(blank=True, help_text='ESP32 key: V5', null=True)),
                ('volt_batt', models.FloatField(blank=True, help_text='ESP32 key: VBatt', null=True)),
                ('volt_solar', models.FloatField(blank=True, help_text='ESP32 key: VSol', null=True)),
                ('volt_dc', models.FloatField(blank=True, help_text='ESP32 key: VDC', null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voltage_readings', to='stations.station')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='idx_voltage_timestamp'), models.Index(fields=['station_code', 'timestamp'], name='idx_voltage_code_time')],
            },
        ),
        migrations.CreateModel(
            name='WeatherReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(default='AWS-UG-001', help_text='Raw station ID string from ESP32 e.g. AWS-UG-001', max_length=50)),
                ('timestamp', models.DateTimeField(help_text='Timestamp from the ESP32 RTC. ESP32 key: Time')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('pressure', models.FloatField(blank=True, help_text='ESP32 key: Press', null=True)),
                ('altitude', models.FloatField(blank=True, help_text='ESP32 key: Alt', null=True)),
                ('temperature', models.FloatField(blank=True, help_text='ESP32 key: Temp', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='ESP32 key: Hum', null=True)),
                ('light', models.FloatField(blank=True, help_text='ESP32 key: Light', null=True)),
                ('soil_moisture', models.FloatField(blank=True, help_text='ESP32 key: SoilM', null=True)),
                ('rain', models.IntegerField(blank=True, help_text='ESP32 key: Rain', null=True)),
                ('wind_speed', models.FloatField(blank=True, help_text='ESP32 key: WSpd', null=True)),
                ('wind_direction', models.IntegerField(blank=True, help_text='ESP32 key: WDir', null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_readings', to='stations.station')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='idx_weather_timestamp'), models.Index(fields=['station_code', 'timestamp'], name='idx_weather_code_time')],
            },
        ),
    ]
