# Generated by Django 5.2.3 on 2026-07-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_station_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('iccid', models.CharField(blank=True, max_length=50)),
                ('data_limit_mb', models.FloatField(default=1024.0)),
                ('data_used_mb', models.FloatField(default=0.0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sim_card', to='stations.station')),
            ],
        ),
    ]
