# Generated by Django 6.0.7 on 2026-07-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_simcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='simcard',
            name='date_loaded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
