# Generated by Django 6.0.6 on 2026-08-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_simcard_date_loaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='battery_temp',
            field=models.FloatField(blank=True, help_text='Battery temperature in Celsius.', null=True),
        ),
        migrations.AddField(
            model_name='voltagereading',
            name='battery_temp',
            field=models.FloatField(blank=True, help_text='ESP32 key: Battery temperature (°C)', null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='rain',
            field=models.FloatField(blank=True, help_text='Rain gauge tip count. ESP32 key: Rain', null=True),
        ),
        migrations.AlterField(
            model_name='weatherreading',
            name='rain',
            field=models.FloatField(blank=True, help_text='ESP32 key: Rain', null=True),
        ),
    ]
