# Generated by Django 6.0.6 on 2026-08-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_sensorreading_battery_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorreading',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='weatherreading',
            name='altitude',
        ),
    ]
