# Generated by Django 6.0.6 on 2026-08-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_remove_sensorreading_altitude_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS stations_benchmarkreading (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                source varchar(100) NOT NULL DEFAULT 'UNMA',
                location varchar(100) NOT NULL DEFAULT '',
                timestamp timestamp with time zone NOT NULL,
                temperature double precision NULL,
                humidity double precision NULL,
                pressure double precision NULL,
                wind_speed double precision NULL,
                wind_direction double precision NULL,
                rain double precision NULL,
                light double precision NULL,
                soil_moisture double precision NULL
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS stations_benchmarkreading;"
        ),
        migrations.RemoveField(
            model_name='benchmarkreading',
            name='light',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='light',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='volt_3v3',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='volt_5v',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='volt_dc',
        ),
        migrations.RemoveField(
            model_name='voltagereading',
            name='volt_3v3',
        ),
        migrations.RemoveField(
            model_name='voltagereading',
            name='volt_5v',
        ),
        migrations.RemoveField(
            model_name='voltagereading',
            name='volt_dc',
        ),
        migrations.RemoveField(
            model_name='weatherreading',
            name='light',
        ),
        migrations.AddField(
            model_name='benchmarkreading',
            name='solar_radiation',
            field=models.FloatField(blank=True, help_text='Solar radiation in W/m²', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='soil_moisture_v',
            field=models.FloatField(blank=True, help_text='Soil moisture sensor voltage in Volts. ESP32 key: SoilM', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='solar_radiation',
            field=models.FloatField(blank=True, help_text='Solar radiation in W/m². ESP32 key: Light / SolRad', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='solar_radiation_v',
            field=models.FloatField(blank=True, help_text='Solar radiation sensor voltage in Volts.', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='wind_direction_v',
            field=models.FloatField(blank=True, help_text='Wind direction sensor voltage in Volts.', null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='soil_moisture_v',
            field=models.FloatField(blank=True, help_text='Soil moisture sensor voltage (V). ESP32 key: SoilM', null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='solar_radiation',
            field=models.FloatField(blank=True, help_text='Solar radiation (W/m²)', null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='solar_radiation_v',
            field=models.FloatField(blank=True, help_text='Solar radiation sensor voltage (V)', null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='wind_direction_v',
            field=models.FloatField(blank=True, help_text='Wind direction sensor voltage (V)', null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='soil_moisture',
            field=models.FloatField(blank=True, help_text='Soil moisture in percent (%).', null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='wind_direction',
            field=models.IntegerField(blank=True, help_text='Wind direction in degrees (0-360). ESP32 key: WDir', null=True),
        ),
        migrations.AlterField(
            model_name='weatherreading',
            name='soil_moisture',
            field=models.FloatField(blank=True, help_text='Soil moisture (%)', null=True),
        ),
    ]
