# Generated by Django 6.0.6 on 2026-09-01 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_remove_benchmarkreading_light_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='gust_count',
            field=models.IntegerField(blank=True, help_text='Number of gust pulses counted', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='gust_span_ms',
            field=models.IntegerField(blank=True, help_text='Time span of gust measurement, ms', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='interval_s',
            field=models.IntegerField(blank=True, help_text='Reporting interval in seconds', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='rain_tips_total',
            field=models.IntegerField(blank=True, help_text='Sum of rain tips across minute buckets', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='wind_gust',
            field=models.FloatField(blank=True, help_text='Peak wind gust speed', null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='wind_pulses_total',
            field=models.IntegerField(blank=True, help_text='Sum of wind pulses across minute buckets', null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='gust_count',
            field=models.IntegerField(blank=True, help_text='Number of gust pulses counted', null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='gust_span_ms',
            field=models.IntegerField(blank=True, help_text='Time span of gust measurement, ms', null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='interval_s',
            field=models.IntegerField(blank=True, help_text='Reporting interval in seconds', null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='rain_tips_total',
            field=models.IntegerField(blank=True, help_text='Sum of rain tips across minute buckets', null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='wind_gust',
            field=models.FloatField(blank=True, help_text='Peak wind gust speed', null=True),
        ),
        migrations.AddField(
            model_name='weatherreading',
            name='wind_pulses_total',
            field=models.IntegerField(blank=True, help_text='Sum of wind pulses across minute buckets', null=True),
        ),
        migrations.CreateModel(
            name='WeatherMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=50)),
                ('minute_start', models.DateTimeField()),
                ('span_s', models.SmallIntegerField(default=60)),
                ('wind_pulses', models.SmallIntegerField()),
                ('rain_tips', models.SmallIntegerField()),
                ('sensor_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='stations.sensorreading')),
                ('weather_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='stations.weatherreading')),
            ],
            options={
                'ordering': ['minute_start'],
                'indexes': [models.Index(fields=['station_code', 'minute_start'], name='idx_wm_station_minute')],
                'constraints': [models.UniqueConstraint(fields=('station_code', 'minute_start'), name='uniq_station_minute')],
            },
        ),
    ]
